### ISSUE TITLE
Access forbidden for the user as cookie validation failed

### ISSUE THREAD

**Issue by valinaga** [timbreitkreutz/omniauth-yahoo#14]
This error starts to come recently.
It popups at `def raw_info` in `yahoo.rb`, trying to get `@raw_info`.
I changed the client/secret and cleaned all cookies with no result.
The exact output for `@raw_info` is this:
`{"error"=>{
        "@lang"=>"en-US", 
        "@uri"=>"http://yahoo.com", 
        "description"=>"Access forbidden for the user as cookie validation failed", 
       "detail"=>"Access forbidden for the user as cookie validation failed"
       }
}`
Any idea will be appreciated.
Thanks.

**Comment by timbreitkreutz** [comment]
@valinaga do you have an isolated test case I can use to reproduce?  Thanks

**Comment by valinaga** [comment]
@timbreitkreutz how to isolate the case?  I use this in my Gemfile:
```
gem "omniauth"
gem "omniauth-yahoo"
```

**Comment by timbreitkreutz** [comment]
A small app that demonstrates the error you're getting?  I am no longer actively using this gem myself unfortunately...

**Comment by timbreitkreutz** [comment]
Stale
