### ISSUE TITLE
Re-prompting for access?

### ISSUE THREAD

**Issue by afrankel** [timbreitkreutz/omniauth-yahoo#4]
When I auth through yahoo I get the Yahoo screen that says 'Click "Agree" to allow sharing of Yahoo! info with MYAPP'.  Underneath that I see:

You are authorizing access to:
Profiles

(since I set up access to Profiles to allow my app to collect the email address).

The problem is that this yahoo page appears everytime I log into my app.   I was looking for something like the google_oauth2 strategy has which prevents re-prompting on every login.  See here for more info (approval_prompt):
https://github.com/zquestz/omniauth-google-oauth2/blob/master/examples/omni_auth.rb

Is this option available or am I not setting up something correctly in yahoo developer?

**Comment by nileshtrivedi** [comment]
This happens for me with V 0.0.5 as well.

**Comment by Luisjavier2008** [comment]
I'm having the same problem can you guys please fix it? if a user give the permissions for the app and logged out when the user login again the application ask for permissions again.

**Comment by timbreitkreutz** [comment]
Can anyone point me to an app that I could test this with (or send me a copy of the code)?

**Comment by timbreitkreutz** [comment]
Closing this as stale.
