### ISSUE TITLE
Unable to retrieve authenticated user's primary email

### ISSUE THREAD

**Issue by rossnoble** [timbreitkreutz/omniauth-yahoo#9]
I think it's the result of Yahoo changing their API, but on every oAuth request, the "primary_email" is always returned as nil for the user's profile.

I've been searching through the Yahoo docs trying to find a different URL to hit, but I haven't found anything that's supposed to return the email.

Anyone else had this problem?

**Comment by timbreitkreutz** [comment]
Did the permissions explain the problem?

**Comment by timbreitkreutz** [comment]
I've actually confirmed that if the Read/Write Public and Private option is selected the email is then available--so I think this is a "feature" of the Yahoo API after all.  Thanks @OpakAlex
